rhyper - z : open -a Zed
# rhyper - r : open -a Rio
# rhyper - k : kitty
rhyper - t : open -a Ghostty
rhyper - e : open -a Telegram
rhyper - w : open -a WhatsApp
rhyper - s : open -a Safari
rhyper - l : open -a Linear
rhyper - m : open -a Music
rhyper - x : open -a Firefox
rhyper - f : open -a Finder
rhyper - g : open -a ChatGPT
rhyper - c : open -a Google\ Chrome

rhyper - 0x32 : kitten quick-access-terminal

rhyper - 1 : issw org.sil.ukelele.keyboardlayout.t.english–ilyabirmantypography
rhyper - 2 : issw org.sil.ukelele.keyboardlayout.t.russian–ilyabirmantypography

# hyper - +
rhyper - 0x1B : $(brew --prefix)/bin/displayplacer "id:37D8832A-2D66-02CA-B9F7-8F30A301B230 res:2560x1664 hz:60 color_depth:8 enabled:true scaling:off origin:(0,0) degree:0" ; killall yabai
rhyper - 0x18 : $(brew --prefix)/bin/displayplacer "id:37D8832A-2D66-02CA-B9F7-8F30A301B230 res:1710x1112 hz:60 color_depth:8 enabled:true scaling:on origin:(0,0) degree:0" ; killall yabai

# hyper |
rhyper - 0x2A : osascript -e 'tell application "System Events" to tell appearance preferences to set dark mode to not dark mode'

# focus window
rhyper - left : yabai -m window --focus west || yabai -m display --focus west
rhyper - right : yabai -m window --focus east || yabai -m display --focus east
rhyper - down : yabai -m window --focus south || yabai -m display --focus south
rhyper - up : yabai -m window --focus north || yabai -m display --focus north

# move window
rhyper + lcmd - right : yabai -m window --warp east || yabai -m window --display east --focus
rhyper + lcmd - left : yabai -m window --warp west || yabai -m window --display west --focus
rhyper + lcmd - up : yabai -m window --warp north || yabai -m window --display north --focus
rhyper + lcmd - down : yabai -m window --warp south || yabai -m window --display south --focus

# swap window
# shift + alt - left : yabai -m window --swap west
# shift + alt - down : yabai -m window --swap south
# shift + alt - up : yabai -m window --swap north
# shift + alt - right : yabai -m window --swap east
